version: '3'

services:
  mysql:
    image: mysql/mysql-server
    container_name: mysql01
    ports:
      - 3307:3307
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: new_db
      MYSQL_USER: root
      MYSQL_PASSWORD: user
